/**
 * cronJobs.ts
 * 
 * Scheduled background jobs for Trade Grow.
 * 
 * Jobs:
 *  - Every 30 min (Mon-Fri 7:30 AM–4:00 PM IST): Check Dhan token expiry and alert via Telegram
 *  - 8:30 AM IST every trading day: Send morning token renewal reminder to Telegram
 * 
 * NOTE: This uses Node.js setInterval (lightweight, no external dep required).
 * For production scale, consider using 'node-cron' package: npm install node-cron
 */

import { sendTelegramAlert } from './telegramAlert';
import { getTokenExpiryMinutes, isTokenExpiringSoon, autoGenerateDhanToken } from './dhanTokenRefresh';

import { autoGenerateFyersToken } from './fyersTokenRefresh';
import { queryOne } from '../db/schema';
import { RmsAutoSquareOffEngine } from '../trading/RmsAutoSquareOffEngine';

let tokenExpiryCheckInterval: NodeJS.Timeout | null = null;
let morningReminderTimeout: NodeJS.Timeout | null = null;
let fyersRenewalInterval: NodeJS.Timeout | null = null;
let misSquareOffTimeout: NodeJS.Timeout | null = null;

/**
 * Checks and auto-renews Fyers Access Token automatically in the background
 */
/**
 * Fyers auto-renewal is DISABLED — Fyers provider is not used.
 */
function startFyersAutoRenewalCheck() {
  // DISABLED: Fyers is not used. Removing this prevents crash-reconnect storms on startup.
  console.log('[CronJobs] ℹ️  Fyers auto-renewal skipped — Fyers provider is disabled.');
}

/**
 * Get milliseconds until the next occurrence of a given IST hour:minute on Mon-Fri.
 */
function getMsUntilISTTime(targetHour: number, targetMinute: number): number {
  // IST = UTC+5:30
  const nowUTC = new Date();
  const nowIST = new Date(nowUTC.getTime() + (5.5 * 60 * 60 * 1000));

  const next = new Date(nowIST);
  next.setHours(targetHour, targetMinute, 0, 0);

  if (next <= nowIST) {
    // Already passed today — schedule for tomorrow
    next.setDate(next.getDate() + 1);
  }

  // Skip weekends (Saturday=6, Sunday=0)
  while (next.getDay() === 0 || next.getDay() === 6) {
    next.setDate(next.getDate() + 1);
  }

  return next.getTime() - nowIST.getTime();
}

/**
 * Schedule the 08:30 AM IST morning Telegram reminder to renew the Dhan token.
 * Recursively re-schedules itself for the next trading day after firing.
 */
function scheduleMorningReminder(getAccessToken: () => string) {
  const msUntilMorning = getMsUntilISTTime(8, 30);
  const hoursUntil = (msUntilMorning / 1000 / 60 / 60).toFixed(1);
  console.log(`[CronJobs] ⏰ Morning token reminder scheduled in ${hoursUntil}h (08:30 AM IST next trading day).`);

  morningReminderTimeout = setTimeout(async () => {
    const token = getAccessToken();
    const minutesLeft = getTokenExpiryMinutes(token);
    const hoursLeft = (minutesLeft / 60).toFixed(1);

    if (minutesLeft <= 0) {
      await sendTelegramAlert(
        `🚨 <b>Trade Grow — Dhan Token EXPIRED!</b>\n\n` +
        `❌ The Dhan access token has expired. Live market data is currently unavailable.\n\n` +
        `🔑 Please:\n` +
        `1. Login to <a href="https://login.dhan.co">https://login.dhan.co</a>\n` +
        `2. Generate a new Access Token\n` +
        `3. Call: <code>POST /api/internal/update-dhan-token</code> with the new token\n\n` +
        `📱 Or use the Trade Grow Admin Panel → Broker Settings`
      );
    } else if (minutesLeft <= 120) {
      await sendTelegramAlert(
        `⚠️ <b>Trade Grow — Dhan Token Expiring Soon!</b>\n\n` +
        `🕐 Token expires in: <b>${hoursLeft} hours (${minutesLeft} minutes)</b>\n\n` +
        `🔑 Please renew before market opens:\n` +
        `1. Login to <a href="https://login.dhan.co">https://login.dhan.co</a>\n` +
        `2. Generate a new Access Token\n` +
        `3. Call: <code>POST /api/internal/update-dhan-token</code>\n\n` +
        `⚡ Token will auto-update once you call the endpoint — no server restart needed.`
      );
    } else {
      await sendTelegramAlert(
        `🌅 <b>Trade Grow — Good Morning! Daily Token Check</b>\n\n` +
        `✅ Dhan token is valid for <b>${hoursLeft} more hours</b>.\n` +
        `📈 Market opens at 09:15 AM IST. All systems operational.`
      );
    }

    // Re-schedule for the next trading day
    scheduleMorningReminder(getAccessToken);
  }, msUntilMorning);
}

/**
 * Schedule the MIS auto square-off engine run at the configured IST time.
 * Re-reads MIS_AUTO_SQUARE_OFF_TIME from system_settings on every reschedule
 * (not cached) so an admin changing it mid-day takes effect the next trading
 * day without a restart. Falls back to '15:15' if the key is missing.
 * Not gated behind Dhan-adapter availability — unlike startCronJobs(), this
 * must run even if the market-data provider failed to initialize, since EOD
 * risk cleanup matters most exactly when other systems are degraded.
 */
async function scheduleMisAutoSquareOff() {
  let hour = 15, minute = 15;
  try {
    const row = await queryOne<any>(`SELECT value FROM system_settings WHERE key = 'MIS_AUTO_SQUARE_OFF_TIME'`);
    const raw = (row?.value || '15:15').trim();
    const match = raw.match(/^(\d{1,2}):(\d{2})$/);
    if (match) {
      hour = parseInt(match[1], 10);
      minute = parseInt(match[2], 10);
    }
  } catch (err: any) {
    console.warn('[CronJobs] Failed to read MIS_AUTO_SQUARE_OFF_TIME, defaulting to 15:15:', err.message);
  }

  const msUntilRun = getMsUntilISTTime(hour, minute);
  console.log(`[CronJobs] 🔒 MIS auto square-off scheduled in ${(msUntilRun / 1000 / 60 / 60).toFixed(1)}h (${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')} IST next trading day).`);

  misSquareOffTimeout = setTimeout(async () => {
    try {
      await RmsAutoSquareOffEngine.run();
    } catch (err: any) {
      console.error('[CronJobs] RMS auto square-off run failed:', err.message);
    }
    // Re-schedule for the next trading day (re-reads config fresh)
    scheduleMisAutoSquareOff();
  }, msUntilRun);
}

/**
 * Start the Dhan token expiry check interval.
 * Checks every 30 minutes. Sends an alert if token expires in <60 minutes.
 */
function startTokenExpiryCheck(getAccessToken: () => string) {
  // Run immediately on start
  const checkNow = async () => {
    const token = getAccessToken();
    const hasAutoCreds = process.env.DHAN_TOTP_SECRET && process.env.DHAN_PIN && process.env.DHAN_CLIENT_ID;

    // Check if token missing or expiring in <60 min
    const isExpiring = !token || isTokenExpiringSoon(token, 60);

    if (isExpiring) {
      if (hasAutoCreds) {
        console.log('[CronJobs] 🔄 Dhan token missing or expiring soon. Attempting automated renewal with TOTP...');
        const res = await autoGenerateDhanToken();
        if (res.success) {
          console.log('[CronJobs] ✅ Dhan token auto-generated & updated successfully!');
          return;
        } else {
          console.warn('[CronJobs] ⚠️ Dhan auto-generation failed:', res.message);
        }
      }

      if (token) {
        const minutesLeft = getTokenExpiryMinutes(token);
        console.warn(`[CronJobs] ⚠️ Dhan token expiring in ${minutesLeft} minutes! Sending Telegram alert...`);
        await sendTelegramAlert(
          `⚠️ <b>Trade Grow — Dhan Token Expiry Alert!</b>\n\n` +
          `🕐 Token expires in: <b>${minutesLeft} minutes</b>\n\n` +
          `🔑 Action required:\n` +
          `1. Login to <a href="https://login.dhan.co">https://login.dhan.co</a>\n` +
          `2. Copy your new Access Token\n` +
          `3. POST to: <code>/api/internal/update-dhan-token</code>\n\n` +
          `Body: <code>{"accessToken": "YOUR_NEW_TOKEN"}</code>`
        );
      }
    } else {
      const minutesLeft = getTokenExpiryMinutes(token);
      if (minutesLeft > 0) {
        console.log(`[CronJobs] ✅ Dhan token healthy. Expires in ${minutesLeft} minutes (~${(minutesLeft / 60).toFixed(1)}h).`);
      }
    }
  };

  checkNow();

  // Check every 30 minutes
  tokenExpiryCheckInterval = setInterval(checkNow, 30 * 60 * 1000);
  console.log('[CronJobs] 🔄 Dhan token expiry check interval started (every 30 minutes with TOTP auto-renewal).');
}

/**
 * Start all cron jobs. Call this from server/src/index.ts after DhanAdapter initializes.
 * @param getAccessToken - A function that returns the current Dhan access token (live)
 */
export function startCronJobs(getAccessToken: () => string) {
  console.log('[CronJobs] 🚀 Starting Trade Grow background cron jobs...');
  startTokenExpiryCheck(getAccessToken);
  scheduleMorningReminder(getAccessToken);
  startFyersAutoRenewalCheck();
}

/**
 * Start the MIS auto square-off scheduler. Called separately from
 * startCronJobs() (see index.ts) — deliberately not gated behind Dhan-adapter
 * availability, since EOD risk cleanup must run regardless of market-data
 * provider health.
 */
export function startMisAutoSquareOffJob() {
  scheduleMisAutoSquareOff();
}

/**
 * Gracefully stop all cron jobs (for clean server shutdown).
 */
export function stopCronJobs() {
  if (tokenExpiryCheckInterval) clearInterval(tokenExpiryCheckInterval);
  if (morningReminderTimeout) clearTimeout(morningReminderTimeout);
  if (fyersRenewalInterval) clearInterval(fyersRenewalInterval);
  if (misSquareOffTimeout) clearTimeout(misSquareOffTimeout);
  console.log('[CronJobs] 🛑 All cron jobs stopped.');
}
