import React from 'react';
import { PriceState } from '../hooks/useTickFreshness';
import { TickSource } from '../types';
import { Wifi, WifiOff, AlertTriangle, Clock, Layers } from 'lucide-react';

export interface PriceBadgeProps {
  state: PriceState;
  source?: TickSource;
  timeSinceLastTick?: number;
  showLabel?: boolean;
  size?: 'sm' | 'md';
  className?: string;
}

export const PriceBadge: React.FC<PriceBadgeProps> = ({
  state,
  source,
  timeSinceLastTick,
  showLabel = true,
  size = 'sm',
  className = '',
}) => {
  let colorBg = 'bg-slate-500';
  let colorDot = 'bg-slate-400';
  let textColor = 'text-slate-500 dark:text-slate-400';
  let borderColor = 'border-slate-500/20';
  let label = 'UNKNOWN';
  let tooltip = '';
  let Icon = Clock;
  let pulse = false;

  const secondsAgo = timeSinceLastTick ? (timeSinceLastTick / 1000).toFixed(1) : undefined;

  switch (state) {
    case 'LIVE':
      colorBg = 'bg-emerald-500/10';
      colorDot = 'bg-emerald-500';
      textColor = 'text-emerald-600 dark:text-emerald-400';
      borderColor = 'border-emerald-500/30';
      label = 'LIVE';
      tooltip = `Live exchange feed connected ${secondsAgo ? `(tick ${secondsAgo}s ago)` : ''}`;
      Icon = Wifi;
      pulse = true;
      break;

    case 'STALE':
      colorBg = 'bg-amber-500/10';
      colorDot = 'bg-amber-500';
      textColor = 'text-amber-600 dark:text-amber-400';
      borderColor = 'border-amber-500/30';
      label = 'STALE';
      tooltip = `Stale price: no tick received for ${secondsAgo ? `${secondsAgo}s` : '> 5s'}`;
      Icon = AlertTriangle;
      break;

    case 'DISCONNECTED':
      colorBg = 'bg-rose-500/10';
      colorDot = 'bg-rose-500';
      textColor = 'text-rose-600 dark:text-rose-400';
      borderColor = 'border-rose-500/30';
      label = 'OFFLINE';
      tooltip = 'Socket disconnected — attempting auto-reconnect';
      Icon = WifiOff;
      break;

    case 'MARKET_CLOSED':
      colorBg = 'bg-slate-500/10';
      colorDot = 'bg-slate-400';
      textColor = 'text-slate-500 dark:text-slate-400';
      borderColor = 'border-slate-500/20';
      label = 'CLOSED';
      tooltip = 'Market closed (NSE hours: 09:15 - 15:30 IST Mon-Fri). Showing last close price.';
      Icon = Clock;
      break;

    case 'SYNTHETIC':
      colorBg = 'bg-purple-500/10';
      colorDot = 'bg-purple-500';
      textColor = 'text-purple-600 dark:text-purple-400';
      borderColor = 'border-purple-500/30';
      
      if (source === 'guard_feed') {
        label = 'GUARD FEED';
        tooltip = 'Secondary NSE Guard Feed price (WS feed tick unverified/stale)';
      } else if (source === 'synthetic_skew') {
        label = 'SYNTHETIC SKEW';
        tooltip = 'Theoretical Black-Scholes price calculated via Dynamic Volatility Skew Model';
      } else {
        label = 'SYNTHETIC';
        tooltip = 'Synthetic / Fallback price generated by backend';
      }
      Icon = Layers;
      break;
  }

  const dotSizeClass = size === 'sm' ? 'w-1.5 h-1.5' : 'w-2 h-2';
  const textCategoryClass = size === 'sm' ? 'text-[9px]' : 'text-[10px]';
  const paddingClass = size === 'sm' ? 'px-1.5 py-0.5' : 'px-2 py-1';

  return (
    <span
      className={`inline-flex items-center gap-1.5 ${paddingClass} rounded-full font-black tracking-wider uppercase border ${colorBg} ${textColor} ${borderColor} transition-colors ${className}`}
      title={tooltip}
    >
      <span className="relative flex items-center justify-center">
        {pulse && (
          <span className={`absolute inline-flex h-full w-full rounded-full ${colorDot} opacity-75 animate-ping`} />
        )}
        <span className={`relative inline-flex rounded-full ${dotSizeClass} ${colorDot}`} />
      </span>

      {showLabel && <span className={textCategoryClass}>{label}</span>}
    </span>
  );
};
